ui_node:
  ros__parameters:
    hsv:
      red:
        h_low: 50
        h_high: 0
        s_low: 0
        s_high: 30
        v_low: 10
        v_high: 0
      blue:
        h_low: 182
        h_high: 0
        s_low: 0
        s_high: 155
        v_low: 95
        v_high: 0
      line:
        h_low: 142
        h_high: 0
        s_low: 0
        s_high: 63
        v_low: 0
        v_high: 0
    topic:
      result_topic: "/vision/result"
      raw_image_topic: "/vision/yolo_image"
      result_image_topic: "/vision/result_image"
      tuning_topic: "/vision/tuning"
      brid_image_topic: "/vision/bird_image"
    node_hz: 15.0
    ui_apply_hz: 15.0

process_node:
  ros__parameters:
    topic:
      input_topic: "/camera1/camera/compressed_image"
      result_topic: "/vision/result"
      result_image_topic: "/vision/result_image"
      tuning_topic: "/vision/tuning"
      brid_image_topic: "/vision/bird_image"
      yolo_image_topic: "/vision/yolo_image"
    node_hz: 30.0
    img_w: 640
    img_h: 480
    bird_img_w: 320
    bird_img_h: 240

    ROBOT_HEIGHT: 555.0 # 490 #475 #505 #545 #755 #544 ##로봇 높이 (mm)
    TILT_L: 0         #65.0 #75.0 //축간 거리
    camera_info_topic: "/camera1/info"
    pan_tilt_status_topic: "/camera1/pan_tilt_status"
    
pan_tilt_camera_node_camera1: #d만들어뒀는데 지금은 안쓰는중
  ros__parameters:
    node_hz: 15.0